import {auth,db} from './firebase-config.js';
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,signInWithPopup,GoogleAuthProvider,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import {ref,set} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js';
import {initLanguage,t,setLang} from './common.js';
initLanguage();
const form=document.querySelector('#authForm'),btn=document.querySelector('#authBtn'),msg=document.querySelector('#msg'),reset=document.querySelector('#resetBtn'),googleBtn=document.querySelector('#googleBtn');
let mode='login';
const refresh=()=>{btn.textContent=t(mode==='login'?'loginBtn':'createBtn');};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));refresh();});
window.addEventListener('languageChanged',refresh);
form.onsubmit=async e=>{e.preventDefault();msg.textContent=t('loading');msg.className='msg';try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(mode==='register'){const c=await createUserWithEmailAndPassword(auth,email,password);await set(ref(db,`shops/${c.user.uid}/shop`),{email,createdAt:Date.now(),allowView:false});location.href='shop-settings.html';}else{await signInWithEmailAndPassword(auth,email,password);location.href='dashboard.html';}}catch(err){msg.textContent=err.message;msg.className='msg error';}};
reset.onclick=async()=>{const e=document.querySelector('#email').value.trim();if(!e){msg.textContent=t('enterEmail');return;}try{await sendPasswordResetEmail(auth,e);msg.textContent=t('passwordResetSent');}catch(x){msg.textContent=x.message;msg.className='msg error';}};
googleBtn.onclick=async()=>{msg.textContent=t('loading');msg.className='msg';try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const result=await signInWithPopup(auth,provider);const user=result.user;await set(ref(db,`shops/${user.uid}/shop`),{email:user.email||'',ownerName:user.displayName||'',photoURL:user.photoURL||'',createdAt:Date.now(),allowView:false},{merge:true});location.href='dashboard.html';}catch(err){msg.textContent=err.code==='auth/popup-closed-by-user'?t('googleCancelled'):err.message;msg.className='msg error';}};
onAuthStateChanged(auth,u=>{if(u&&location.pathname.endsWith('/index.html')){} });
refresh();
