import {db} from './firebase-config.js';
import {ref,get,push,set,remove} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js';
import {requireAuth,today,money,esc,initLanguage,t} from './common.js';
initLanguage();let uid,cid,customer,mode='credit';
requireAuth(async u=>{uid=u.uid;cid=new URLSearchParams(location.search).get('id');if(!cid)return location.href='customers.html';customer=(await get(ref(db,`shops/${uid}/customers/${cid}`))).val();if(!customer)return location.href='customers.html';render();});
function calc(){let cr=0,pa=0;Object.values(customer.transactions||{}).forEach(x=>x.type==='credit'?cr+=Number(x.amount)||0:pa+=Number(x.amount)||0);return{cr,pa,due:cr-pa}}
async function syncPortal(){if(!customer.online||!customer.customerAccessKey)return;const shop=(await get(ref(db,`shops/${uid}/shop`))).val()||{};const existing=(await get(ref(db,`customerAccess/${customer.customerAccessKey}`))).val()||{};await set(ref(db,`customerAccess/${customer.customerAccessKey}`),{enabled:true,shops:{...(existing.shops||{}),[uid]:{shopName:shop.shopName||t('shop'),shopPhoto:shop.shopPhoto||'',customerId:cid,account:{name:customer.name||'',mobile:customer.mobile||'',address:customer.address||'',photo:customer.photo||'',transactions:customer.transactions||{}}}}})}
function render(){const x=calc();document.querySelector('#credit').textContent=money(x.cr);document.querySelector('#paid').textContent=money(x.pa);document.querySelector('#due').textContent=money(x.due);document.querySelector('#customerHead').innerHTML=`<div><p class="eyebrow">${t('customerLedger')}</p><div class="customer-headline"><div class="avatar customer-photo large">${customer.photo?`<img src="${customer.photo}" alt="">`:esc((customer.name||'?')[0].toUpperCase())}</div><div><h1>${esc(customer.name)}</h1><p>📱 ${esc(customer.mobile)} ${customer.address?` • 📍 ${esc(customer.address)}`:''}</p></div></div><div class="top-right customer-pin-owner"><span class="portal-badge">${x.due>0?t('due'):t('paid')}</span><span class="pin-owner">🔐 ${t('pin')}: <b id="ownerPin">••••••</b> <button class="ghost small-action" id="toggleOwnerPin" type="button">${t('showPin')}</button></span></div>`;const toggle=document.querySelector('#toggleOwnerPin'); if(toggle) toggle.onclick=()=>{const el=document.querySelector('#ownerPin');const shown=el.textContent!=='••••••';el.textContent=shown?'••••••':(customer.customerPin||'—');toggle.textContent=shown?t('showPin'):t('hidePin')};const rows=Object.entries(customer.transactions||{}).sort((a,b)=>(b[1].date||'').localeCompare(a[1].date||'')).map(([id,x])=>`<tr><td>${esc(x.date||'')}</td><td>${esc(x.item||t('payment'))}</td><td>${x.type==='credit'?`${esc(x.qty||1)} × ${money((Number(x.amount)||0)/(Number(x.qty)||1))}`:t('payment')}</td><td class="${x.type==='credit'?'credit':'paid'}">${x.type==='credit'?money(x.amount):'-'+money(x.amount)}</td><td><button class="ghost small-action" data-delete="${id}">×</button></td></tr>`).join('');document.querySelector('#entries').innerHTML=`<table><thead><tr><th>${t('date')}</th><th>${t('item')}</th><th>${t('quantity')}</th><th>${t('amount')}</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="5" class="empty">${t('noTransactions')}</td></tr>`}</tbody></table>`;document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this transaction?'))return;await remove(ref(db,`shops/${uid}/customers/${cid}/transactions/${b.dataset.delete}`));customer=(await get(ref(db,`shops/${uid}/customers/${cid}`))).val();await syncPortal();render()})}
function openModal(m){mode=m;document.querySelector('#modalTitle').textContent=m==='credit'?t('addCredit'):t('addPayment');document.querySelector('#item').value=m==='credit'?'':t('paymentNote');document.querySelector('#qtyWrap').classList.toggle('hidden',m!=='credit');document.querySelector('#modal').classList.remove('hidden');document.querySelector('#date').value=today();document.querySelector('#amount').value=''}
document.querySelector('#entryBtn').onclick=()=>openModal('credit');document.querySelector('#paymentBtn').onclick=()=>openModal('payment');document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.add('hidden');
document.querySelector('#entryForm').onsubmit=async e=>{e.preventDefault();const amount=Number(document.querySelector('#amount').value);if(!(amount>0))return;const id=push(ref(db,`shops/${uid}/customers/${cid}/transactions`)).key;await set(ref(db,`shops/${uid}/customers/${cid}/transactions/${id}`),{type:mode,item:document.querySelector('#item').value.trim()||t('paymentNote'),qty:Number(document.querySelector('#qty').value)||1,amount,date:document.querySelector('#date').value,createdAt:Date.now()});customer=(await get(ref(db,`shops/${uid}/customers/${cid}`))).val();await syncPortal();document.querySelector('#modal').classList.add('hidden');render()};window.addEventListener('languageChanged',()=>location.reload());
